import { writeFileSync } from "node:fs";
import type { Adapter, Builder } from "@sveltejs/kit";

/**
 * Per-category Cache-Control header values.
 *
 * Each key targets a different class of static response.
 * Set to `false` to skip setting any Cache-Control header for that category.
 */
export interface CacheControlOptions {
	/** Content-hashed assets under `/_app/immutable/`.
	 *  @default "public, immutable, max-age=31536000" */
	immutable?: string | false;

	/** Prerendered HTML pages (known at build time from SvelteKit's prerender list).
	 *  @default "public, max-age=600, stale-while-revalidate=86400" */
	prerendered?: string | false;

	/** Unhashed static files — favicon, fonts, images from SvelteKit's `static/` dir.
	 *  @default "public, max-age=86400" */
	assets?: string | false;
}

/**
 * Configuration options for the SvelteKit Demino adapter.
 */
export interface AdapterOptions {
	/** Output directory for the generated handler and assets. @default "build" */
	out?: string;

	/** Cache-Control headers for static responses served from disk.
	 *  SSR responses are not affected — use SvelteKit's `handle` hook for those. */
	cacheControl?: CacheControlOptions;
}

export const CACHE_DEFAULTS: Required<CacheControlOptions> = {
	immutable: "public, immutable, max-age=31536000",
	prerendered: "public, max-age=600, stale-while-revalidate=86400",
	assets: "public, max-age=86400",
};

/**
 * Creates a SvelteKit adapter that produces a Deno-compatible request handler.
 *
 * The adapter generates a `handler.js` file (plus `client/` and `server/` directories)
 * that can be imported by any Deno server using the standard `Deno.ServeHandler` signature,
 * including {@link https://jsr.io/@marianmeres/demino demino}.
 *
 * @param options - Adapter configuration.
 * @returns A SvelteKit `Adapter` object.
 *
 * @example
 * ```js
 * // svelte.config.js
 * import adapter from "@marianmeres/sveltekit-adapter-demino";
 *
 * export default { kit: { adapter: adapter({ out: "build" }) } };
 * ```
 */
export default function adapter(options: AdapterOptions = {}): Adapter {
	const { out = "build", cacheControl: cc = {} } = options;
	const cacheControl = {
		immutable: cc.immutable ?? CACHE_DEFAULTS.immutable,
		prerendered: cc.prerendered ?? CACHE_DEFAULTS.prerendered,
		assets: cc.assets ?? CACHE_DEFAULTS.assets,
	};

	return {
		name: "adapter-demino",

		async adapt(builder: Builder) {
			const tmp = builder.getBuildDirectory("adapter-demino");

			builder.rimraf(tmp);
			builder.mkdirp(tmp);
			builder.rimraf(out);
			builder.mkdirp(out);

			// Static assets (/_app/*, static/ contents) + prerendered HTML
			// merged into a single `client` dir so one serveDir call handles them.
			builder.log.minor("Writing client assets…");
			builder.writeClient(`${out}/client`);

			builder.log.minor("Writing prerendered pages…");
			builder.writePrerendered(`${out}/client`);

			// Server-side SvelteKit runtime
			builder.log.minor("Writing server…");
			builder.writeServer(`${out}/server`);

			// Generate handler.js with the manifest inlined
			const manifest = builder.generateManifest({
				relativePath: "./server",
			});

			const redirects = JSON.stringify([...builder.prerendered.redirects]);
			const prerenderedPages = JSON.stringify([
				...builder.prerendered.pages.keys(),
			]);

			// Resolve false → null for JSON serialization
			const ccJson = JSON.stringify({
				immutable: cacheControl.immutable || null,
				prerendered: cacheControl.prerendered || null,
				assets: cacheControl.assets || null,
			});

			const handlerSrc = generateHandler(manifest, redirects, prerenderedPages, ccJson);
			writeFileSync(`${out}/handler.js`, handlerSrc, "utf-8");

			builder.log.minor(`adapter-demino: output written to ./${out}/`);
		},
	};
}

/**
 * Named export alias for the {@link adapter default} adapter factory.
 */
export { adapter };

function generateHandler(
	manifest: string,
	redirects: string,
	prerenderedPages: string,
	cacheControl: string,
): string {
	return `\
// Generated by adapter-demino — do not edit manually.
// Runs in Deno. Import this from your demino/Deno server.
import { Server } from './server/index.js';
import { serveDir } from 'jsr:@std/http/file-server';
import { join, fromFileUrl } from 'jsr:@std/path';

const server = new Server(${manifest});

const __dir = fromFileUrl(new URL('.', import.meta.url));
const clientDir = join(__dir, 'client');

await server.init({
	env: Deno.env.toObject(),
	read(file) {
		try {
			return Deno.openSync(join(clientDir, file));
		} catch {
			return null;
		}
	},
});

const prerenderedRedirects = new Map(${redirects});
const prerenderedPages = new Set(${prerenderedPages});
const cacheControl = ${cacheControl};

/**
 * Drop-in SvelteKit request handler for demino (or any Deno.ServeHandler).
 *
 * @param {Request} req
 * @param {Deno.ServeHandlerInfo} info
 * @returns {Promise<Response>}
 */
export async function handler(req, info) {
	const url = new URL(req.url);

	// 1. Handle prerendered trailing-slash redirects.
	const redirect = prerenderedRedirects.get(url.pathname);
	if (redirect) {
		return new Response(null, {
			status: redirect.status,
			headers: { location: redirect.location },
		});
	}

	// 2. Serve static assets & prerendered HTML from the client dir.
	//    Only for GET/HEAD — other methods (POST, PUT, etc.) go straight to SSR.
	//    serveDir returns 405 for HEAD, so we convert HEAD→GET and strip the body.
	if (req.method === 'GET' || req.method === 'HEAD') {
		const fileReq = req.method === 'HEAD'
			? new Request(req.url, { method: 'GET', headers: req.headers })
			: req;
		const staticRes = await serveDir(fileReq, {
			fsRoot: clientDir,
			quiet: true,
			enableCors: false,
		});

		if (staticRes.status !== 404) {
			const isHead = req.method === 'HEAD';

			// Determine which cache category this static response belongs to.
			let cc = null;
			if (url.pathname.startsWith('/_app/immutable/')) {
				cc = cacheControl.immutable;
			} else if (prerenderedPages.has(url.pathname) || prerenderedPages.has(url.pathname + '/')) {
				cc = cacheControl.prerendered;
			} else {
				cc = cacheControl.assets;
			}

			if (cc) {
				const headers = new Headers(staticRes.headers);
				headers.set('Cache-Control', cc);
				return new Response(isHead ? null : staticRes.body, {
					status: staticRes.status,
					statusText: staticRes.statusText,
					headers,
				});
			}

			if (isHead) {
				return new Response(null, {
					status: staticRes.status,
					statusText: staticRes.statusText,
					headers: staticRes.headers,
				});
			}
			return staticRes;
		}
	}

	// 3. Everything else goes through SvelteKit's SSR engine.
	return server.respond(req, {
		getClientAddress() {
			return info?.remoteAddr?.hostname ?? '127.0.0.1';
		},
		platform: { info },
	});
}
`;
}
