import { writeFileSync } from "node:fs";
import type { Adapter, Builder } from "@sveltejs/kit";

export interface AdapterOptions {
	/** Output directory (default: "build") */
	out?: string;
}

export default function adapter(options: AdapterOptions = {}): Adapter {
	const { out = "build" } = options;

	return {
		name: "adapter-demino",

		async adapt(builder: Builder) {
			const tmp = builder.getBuildDirectory("adapter-demino");

			builder.rimraf(tmp);
			builder.mkdirp(tmp);
			builder.rimraf(out);
			builder.mkdirp(out);

			// Static assets (/_app/*, static/ contents) + prerendered HTML
			// merged into a single `client` dir so one serveDir call handles them.
			builder.log.minor("Writing client assets…");
			builder.writeClient(`${out}/client`);

			builder.log.minor("Writing prerendered pages…");
			builder.writePrerendered(`${out}/client`);

			// Server-side SvelteKit runtime
			builder.log.minor("Writing server…");
			builder.writeServer(`${out}/server`);

			// Generate handler.js with the manifest inlined
			const manifest = builder.generateManifest({
				relativePath: "./server",
			});

			const redirects = JSON.stringify([...builder.prerendered.redirects]);
			const handlerSrc = generateHandler(manifest, redirects);
			writeFileSync(`${out}/handler.js`, handlerSrc, "utf-8");

			builder.log.minor(`adapter-demino: output written to ./${out}/`);
		},
	};
}

export { adapter };

function generateHandler(manifest: string, redirects: string): string {
	return `\
// Generated by adapter-demino — do not edit manually.
// Runs in Deno. Import this from your demino/Deno server.
import { Server } from './server/index.js';
import { serveDir } from 'jsr:@std/http/file-server';
import { join, fromFileUrl } from 'jsr:@std/path';

const server = new Server(${manifest});

const __dir = fromFileUrl(new URL('.', import.meta.url));
const clientDir = join(__dir, 'client');

await server.init({
	env: Deno.env.toObject(),
	read(file) {
		try {
			return Deno.openSync(join(clientDir, file));
		} catch {
			return null;
		}
	},
});

const prerenderedRedirects = new Map(${redirects});

/**
 * Drop-in SvelteKit request handler for demino (or any Deno.ServeHandler).
 *
 * @param {Request} req
 * @param {Deno.ServeHandlerInfo} info
 * @returns {Promise<Response>}
 */
export async function handler(req, info) {
	const url = new URL(req.url);

	// 1. Handle prerendered trailing-slash redirects.
	const redirect = prerenderedRedirects.get(url.pathname);
	if (redirect) {
		return new Response(null, {
			status: redirect.status,
			headers: { location: redirect.location },
		});
	}

	// 2. Serve static assets & prerendered HTML from the client dir.
	//    serveDir returns 404 when the file is not found, so we fall through.
	const staticRes = await serveDir(req, {
		fsRoot: clientDir,
		quiet: true,
		enableCors: false,
	});

	if (staticRes.status !== 404) {
		// Cache immutable assets (content-hashed by SvelteKit) forever.
		if (url.pathname.startsWith('/_app/immutable/')) {
			const headers = new Headers(staticRes.headers);
			headers.set('Cache-Control', 'public, immutable, max-age=31536000');
			return new Response(staticRes.body, {
				status: staticRes.status,
				statusText: staticRes.statusText,
				headers,
			});
		}
		return staticRes;
	}

	// 3. Everything else goes through SvelteKit's SSR engine.
	return server.respond(req, {
		getClientAddress() {
			return info?.remoteAddr?.hostname ?? '127.0.0.1';
		},
		platform: { info },
	});
}
`;
}
